name: 部署到測試環境

# 觸發條件：只有 staging 分支的 push 和 pull request 會觸發
on:
  push:
    branches:
      - staging
  # pull_request:
  #   branches:
  #     - staging

jobs:
  build-and-deploy:
    name: 建構和部署到測試環境
    runs-on: [ubuntu-latest]
    container: 
      image: node:20.15.1
      volumes:
        - /home/delta/sepms/www:/home/delta/sepms/www

    env:
      DEPLOY_PATH: /home/delta/sepms/www

    steps:
      # 檢出程式碼
      - name: 檢出程式碼
        uses: actions/checkout@v4
        
      # 快取 node_modules
      - name: 快取 node_modules
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-
        
      # 快取 npm 全域快取
      - name: 快取 npm 全域快取
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-cache-${{ runner.os }}-

      # 安裝相依套件
      - name: 安裝相依套件
        run: |
          if [ "${{ steps.node-modules-cache.outputs.cache-hit }}" = "true" ]; then
            echo "✓ 使用快取的 node_modules"
          else
            echo "✗ 快取未命中，執行 npm ci..."
            npm ci --prefer-offline --no-audit --no-fund
            npm install @rollup/rollup-linux-x64-gnu
          fi
          
      # 確認 node_modules 大小（選用）
      - name: 顯示 node_modules 大小
        run: du -sh node_modules | cut -f1
          
      # 顯示快取狀態
      # - name: 顯示快取狀態
      #   run: |
      #     if [ "${{ steps.cache-dependencies.outputs.cache-hit }}" = "true" ]; then
      #       echo "✓ 使用快取的 node_modules"
      #       echo "快取節省的時間約 2-5 分鐘"
      #     else
      #       echo "✓ 重新安裝相依套件並建立快取"
      #     fi
          
      #     echo "目前 node_modules 內容："
      #     ls -la node_modules | head -10
          
      # 執行 lint 檢查
      # - name: 執行 ESLint 檢查
      #   run: npm run lint
        
      # 建構專案
      - name: 建構專案
        run: npm run build
        
      # 檢查建構結果
      - name: 檢查建構結果
        run: |
          if [ ! -d "dist" ]; then
            echo "錯誤：dist 目錄不存在"
            exit 1
          fi
          
          if [ ! "$(ls -A dist)" ]; then
            echo "錯誤：dist 目錄為空"
            exit 1
          fi
          
          echo "建構成功，dist 目錄內容："
          ls -la dist/
          
      # 備份現有檔案（如果存在）
      - name: 備份現有檔案
        run: |
          BACKUP_DIR="${DEPLOY_PATH}_backup_$(date +%Y%m%d_%H%M%S)"
          if [ -d "$DEPLOY_PATH" ] && [ "$(ls -A $DEPLOY_PATH)" ]; then
            echo "備份現有檔案到 $BACKUP_DIR"
            cp -r "$DEPLOY_PATH" "$BACKUP_DIR"
            echo "備份完成"
            
            # 清理舊備份，只保留最新的3個
            echo "清理舊備份檔案..."
            BACKUP_BASE_DIR=$(dirname "$DEPLOY_PATH")
            BACKUP_PATTERN="$(basename "$DEPLOY_PATH")_backup_*"
            
            # 找到所有備份目錄並按時間排序，刪除超過3個的舊備份
            ls -dt "$BACKUP_BASE_DIR"/$BACKUP_PATTERN 2>/dev/null | tail -n +4 | while read old_backup; do
              if [ -d "$old_backup" ]; then
                echo "刪除舊備份: $old_backup"
                rm -rf "$old_backup"
              fi
            done
            
            echo "備份清理完成，目前保留的備份："
            ls -dt "$BACKUP_BASE_DIR"/$BACKUP_PATTERN 2>/dev/null | head -3
          else
            echo "目標目錄不存在或為空，跳過備份"
          fi
          
      # 建立目標目錄（如果不存在）
      - name: 建立目標目錄
        run: |
          mkdir -p "$DEPLOY_PATH"
          echo "目標目錄已準備就緒: $DEPLOY_PATH"
          
      # 清理目標目錄
      - name: 清理目標目錄
        run: |
          if [ -d "$DEPLOY_PATH" ]; then
            rm -rf "$DEPLOY_PATH"/*
            echo "目標目錄已清理"
          fi
          
      # 部署檔案到測試環境
      - name: 部署檔案到測試環境
        run: |
          echo "開始部署檔案..."
          cp -r dist/* "$DEPLOY_PATH"/
          echo "部署完成"
          
      # 驗證部署結果
      - name: 驗證部署結果
        run: |
          echo "驗證部署結果..."
          if [ ! -d "$DEPLOY_PATH" ]; then
            echo "錯誤：目標目錄不存在"
            exit 1
          fi
          
          if [ ! "$(ls -A $DEPLOY_PATH)" ]; then
            echo "錯誤：目標目錄為空"
            exit 1
          fi
          
          echo "部署驗證成功，目標目錄內容："
          ls -la "$DEPLOY_PATH"/
          
          # 檢查重要檔案是否存在
          if [ -f "$DEPLOY_PATH/index.html" ]; then
            echo "✓ index.html 檔案存在"
          else
            echo "⚠ 警告：index.html 檔案不存在"
          fi
          
      # 設定檔案權限
      - name: 設定檔案權限
        run: |
          echo "設定檔案權限..."
          find "$DEPLOY_PATH" -type f -exec chmod 644 {} \;
          find "$DEPLOY_PATH" -type d -exec chmod 755 {} \;
          echo "權限設定完成"
          
      # 顯示部署摘要
      - name: 顯示部署摘要
        run: |
          echo "===================="
          echo "部署摘要"
          echo "===================="
          echo "專案名稱: sepms-frontend"
          echo "分支: ${{ github.ref_name }}"
          echo "提交: ${{ github.sha }}"
          echo "部署時間: $(date)"
          echo "目標目錄: $DEPLOY_PATH"
          echo "檔案數量: $(find "$DEPLOY_PATH" -type f | wc -l)"
          echo "總大小: $(du -sh "$DEPLOY_PATH" | cut -f1)"
          echo "===================="
